# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches:
      - develop
      - 'migration/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js 14.17.3
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.3

    - run: npm ci
    - run: npm test -- --coverage
    - run: npm run tsc
